Use Schema.get_attribute rather than utils.get_value in Relationship
marshmallow-code/marshmallow-jsonapi pull request #74
Opened 2017-03-28 14:28 UTC by scmmmh

When using include_resource_linkage in relationships the code used utils.get_value to get the "id" attribute's value. However, I believe that it should use the link Schema's get_attribute method to enable schemas to override how the attribute is accessed (as is the case for all scalar attributes).

If the Schema's get_attribute has not been overridden, then this will change nothing in the code's behaviour. If it has been overridden, then the behaviour is now consistent.

2017-03-28 14:33 UTC, scmmmh commented
Ignore for the moment, while I check the failing tests.

2017-03-28 15:03 UTC, scmmmh commented
Fixed the issues (I was running with the dev marschmallow 3).
This will now work with marshmallow 2.13, but obviously fails for 3.
Happy for any guidance to make it pass in both scenarios.

2017-03-28 15:12 UTC, scmmmh commented
Now passes for both conditions, but includes an at-runtime check for the marshmallow version. Not the most elegant solution, but I am stuck for anything else.

2017-03-29 12:36 UTC, sloria requested changes
Thanks @scmmmh for the PR! My main concern is the backwards-incompatibility, but that can be addressed. Could you also add a new test for this behavior?

Once those are done, this is good to merge.

2017-03-29 12:36 UTC, sloria commented on tests/test_fields.py
> +            include_resource_linkage=True, type_='people', schema='PostSchema'
This indicates a breaking change. Before this PR, `schema` was only a necessary argument if passing `include_data=True`. Could you add a check to see if a schema is available before trying to use its `get_attribute` method?

2017-03-29 12:36 UTC, sloria commented on marshmallow_jsonapi/fields.py
> +                'id': _stringify(self.schema.get_attribute(value, self.id_field, value)
There's enough duplicated logic here that it might be worth separating this into a private helper (e.g. `_get_id(object)`).

2017-03-30 09:49 UTC, scmmmh commented
I had misremembered that as the schema also being required for include_resource_linkage.

I have added a _get_id method to the Relationship. I just wonder whether this is better factored out as a more generic schema_get_value function into utils, which would allow for a dynamic definition of the method, as with the base get_value function?

I have added three test cases so that it is tested both with and without the schema attribute.

2017-04-01 20:35 UTC, sloria requested changes
Thanks for making those changes. Factoring out the code to a utility function isn't a bad idea, but I think it's unnecessary indirection for now; after all, it will only be used in one place.

Just one suggested change, and I think this is good to go.

2017-04-01 20:35 UTC, sloria commented on marshmallow_jsonapi/fields.py
> +            except ValueError:
I realize this handles the `ValueError` raised by `self.schema`, but there's a risk we might be swallowing a `ValueError`  raised in `get_attribute`. Therefore, I think LBYL is more appropriate in this case:

```python
if self.__schema:
    return self.schema.get_attribute(...)
```

2017-04-02 08:21 UTC, scmmmh commented
I had not considered that. I have made the change.

2017-04-02 13:43 UTC, sloria commented on tests/test_fields.py
> +            include_resource_linkage=True, type_='people', schema='PostSchema'
Does this test fail without your change? `PostSchema` does not override `get_attribute`.

2017-04-03 06:52 UTC, scmmmh commented on tests/test_fields.py
> +            include_resource_linkage=True, type_='people', schema='PostSchema'
I do not believe it should, as the base Schema provides a get_attribute implementation which simply uses the utils.get_value function. Do you want me to add a test case with schema that overrides get_attribute?

2017-04-03 06:55 UTC, sloria commented on tests/test_fields.py
> +            include_resource_linkage=True, type_='people', schema='PostSchema'
@scmmmh Yes, we need tests that would fail without your new code

2017-04-03 07:01 UTC, scmmmh commented on tests/test_fields.py
> +            include_resource_linkage=True, type_='people', schema='PostSchema'
Will do.

2017-04-27 06:53 UTC, closed without merging